import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import { Empty, ErrorState, Loading } from '../components/Ui'
import type { Watchlist } from '../types/api'

const listingPath = (symbol: string, exchange: string | null) => `/stocks/${encodeURIComponent(symbol)}${exchange ? `?exchange=${encodeURIComponent(exchange)}` : ''}`

export function WatchlistsPage() {
  const [watchlists, setWatchlists] = useState<Watchlist[]>([]); const [name, setName] = useState(''); const [symbol, setSymbol] = useState<Record<number, string>>({}); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); setError(''); try { setWatchlists(await api.watchlists() as Watchlist[]) } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to load watchlists.') } finally { setLoading(false) } }
  useEffect(() => { api.watchlists().then((items) => setWatchlists(items as Watchlist[])).catch((err) => setError(err instanceof ApiError ? err.message : 'Unable to load watchlists.')).finally(() => setLoading(false)) }, [])
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; setError(''); try { await api.createWatchlist(name.trim()); setName(''); setMessage('Watchlist created.'); await load() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to create watchlist.') } }
  const add = async (id: number) => { const value = symbol[id]?.trim(); if (!value) return; const [rawSymbol, rawExchange] = value.split(':'); setError(''); try { await api.addWatchlistStock(id, rawSymbol, rawExchange); setSymbol((current) => ({ ...current, [id]: '' })); setMessage('Stock added to watchlist.'); await load() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to add stock.') } }
  const remove = async (id: number, stock: string, exchange: string | null) => { if (!confirm(`Remove ${stock} from this watchlist?`)) return; try { await api.removeWatchlistStock(id, stock, exchange); await load() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to remove stock.') } }
  const removeList = async (id: number) => { if (!confirm('Delete this watchlist?')) return; try { await api.deleteWatchlist(id); await load() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to delete watchlist.') } }
  return <><section className="page-heading"><div><p className="eyebrow">Watchlists</p><h1>Keep an eye on ideas</h1><p className="muted">Organize stocks before recording a transaction.</p></div></section><form className="inline-form" onSubmit={create}><input placeholder="New watchlist name" value={name} onChange={(e) => setName(e.target.value)} required /><button className="primary">Create watchlist</button></form>{message && <p className="form-success">{message}</p>}{error && <ErrorState message={error} />}{loading ? <Loading /> : watchlists.length === 0 ? <Empty>No watchlists yet. Create one above to get started.</Empty> : <div className="watchlist-grid">{watchlists.map((watchlist) => <article className="panel" key={watchlist.id}><div className="panel-heading"><div><h2>{watchlist.name}</h2><p className="muted">{watchlist.stocks.length} {watchlist.stocks.length === 1 ? 'stock' : 'stocks'}</p></div><button className="danger-link" onClick={() => void removeList(watchlist.id)}>Delete</button></div><div className="symbol-list">{watchlist.stocks.length ? watchlist.stocks.map((stock) => <div key={`${stock.symbol}-${stock.exchange}`}><Link to={listingPath(stock.symbol, stock.exchange)}><strong>{stock.symbol}</strong><small>{stock.name}</small></Link><span>{stock.exchange || '—'} · {stock.currency}</span><div><Link className="link-button" to={`/trade?side=buy&symbol=${encodeURIComponent(stock.symbol)}${stock.exchange ? `&exchange=${encodeURIComponent(stock.exchange)}` : ''}`}>Buy</Link><button className="link-button" onClick={() => void remove(watchlist.id, stock.symbol, stock.exchange)}>Remove</button></div></div>) : <p className="muted">No stocks in this watchlist.</p>}</div><div className="inline-form compact"><input placeholder="Add symbol, e.g. AAPL or TCS:NSE" value={symbol[watchlist.id] ?? ''} onChange={(e) => setSymbol((current) => ({ ...current, [watchlist.id]: e.target.value }))} /><button className="secondary" type="button" onClick={() => void add(watchlist.id)}>Add stock</button></div></article>)}</div>}</>
}
